"""Rolang dependency lock file (rolang.lock) parsing and serialization."""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

LOCK_FILENAME = "rolang.lock"
LOCK_VERSION = 1


@dataclass
class LockedPackage:
    """A pinned dependency entry in the lock file."""
    name: str
    version: str
    source: str            # "path:../foo", "git:https://...?tag=v1.0"
    checksum: Optional[str] = None    # sha256 hex for registry packages
    dependencies: list[str] = field(default_factory=list)


@dataclass
class LockFile:
    version: int = LOCK_VERSION
    packages: list[LockedPackage] = field(default_factory=list)

    # ── Loaders ───────────────────────────────────────────────────────────────

    @classmethod
    def load(cls, path: Path) -> "LockFile":
        lock_path = path if path.name == LOCK_FILENAME else path / LOCK_FILENAME
        if not lock_path.exists():
            return cls()
        with open(lock_path, "rb") as fh:
            raw = tomllib.load(fh)
        return cls._from_dict(raw)

    @classmethod
    def _from_dict(cls, data: dict) -> "LockFile":
        version = data.get("version", LOCK_VERSION)
        packages = [
            LockedPackage(
                name=pkg["name"],
                version=pkg["version"],
                source=pkg["source"],
                checksum=pkg.get("checksum"),
                dependencies=pkg.get("dependencies", []),
            )
            for pkg in data.get("package", [])
        ]
        return cls(version=version, packages=packages)

    # ── Mutation ──────────────────────────────────────────────────────────────

    def find(self, name: str) -> Optional[LockedPackage]:
        """Return the locked package with *name*, or None."""
        return next((p for p in self.packages if p.name == name), None)

    def upsert(self, pkg: LockedPackage) -> None:
        """Insert or replace the entry for *pkg.name*."""
        for i, existing in enumerate(self.packages):
            if existing.name == pkg.name:
                self.packages[i] = pkg
                return
        self.packages.append(pkg)

    def remove(self, name: str) -> bool:
        """Remove the entry for *name*. Returns True if it was present."""
        before = len(self.packages)
        self.packages = [p for p in self.packages if p.name != name]
        return len(self.packages) < before

    # ── Serialization ─────────────────────────────────────────────────────────

    def save(self, dest: Path) -> None:
        lock_path = dest if dest.name == LOCK_FILENAME else dest / LOCK_FILENAME
        lock_path.write_text(self._to_toml(), encoding="utf-8")

    def _to_toml(self) -> str:
        lines = [
            "# This file is automatically generated by the Rolang toolchain.",
            "# Do not edit manually. Commit this file to version control.",
            "",
            f"version = {self.version}",
            "",
        ]
        for pkg in sorted(self.packages, key=lambda p: p.name):
            lines.append("[[package]]")
            lines.append(f'name = "{pkg.name}"')
            lines.append(f'version = "{pkg.version}"')
            lines.append(f'source = "{pkg.source}"')
            if pkg.checksum:
                lines.append(f'checksum = "{pkg.checksum}"')
            if pkg.dependencies:
                deps_str = ", ".join(f'"{d}"' for d in sorted(pkg.dependencies))
                lines.append(f"dependencies = [{deps_str}]")
            lines.append("")
        return "\n".join(lines)
