import std.string_builder

// Ordered entries with a linear-probe hash index; allocations follow the bootstrap arena.
pub def emit_dict_runtime(output: StringBuilder) -> Void {
    output.append_line("struct rl_dict { rl_vec *keys, *values; uint32_t *buckets; size_t capacity; int kind; };");
    output.append_line("static uint64_t rl_dict_hash(rl_dict *d, rl_slot key) {");
    output.append_line("    uint64_t h;");
    output.append_line("    if (d->kind == 1) {");
    output.append_line("        rl_string *s = key.reference; h = UINT64_C(14695981039346656037);");
    output.append_line("        if (s) for (int64_t i = 0; i < s->length; ++i) { h ^= s->data[i]; h *= UINT64_C(1099511628211); }");
    output.append_line("        return h;");
    output.append_line("    }");
    output.append_line("    h = d->kind == 2 ? (uint64_t)(uintptr_t)key.reference : (uint64_t)key.number;");
    output.append_line("    h ^= h >> 30; h *= UINT64_C(0xbf58476d1ce4e5b9); h ^= h >> 27;");
    output.append_line("    h *= UINT64_C(0x94d049bb133111eb); return h ^ (h >> 31);");
    output.append_line("}");
    output.append_line("static int rl_dict_equal(rl_dict *d, rl_slot a, rl_slot b) {");
    output.append_line("    if (d->kind == 1) {");
    output.append_line("        if (a.reference == b.reference) return 1;");
    output.append_line("        if (!a.reference || !b.reference) return 0;");
    output.append_line("        return rl_string_compare(a.reference, b.reference) == 0;");
    output.append_line("    }");
    output.append_line("    return d->kind == 2 ? a.reference == b.reference : a.number == b.number;");
    output.append_line("}");
    output.append_line("static size_t rl_dict_bucket(rl_dict *d, rl_slot key) {");
    output.append_line("    size_t p = (size_t)rl_dict_hash(d, key) & (d->capacity - 1);");
    output.append_line("    while (d->buckets[p] && !rl_dict_equal(d, d->keys->data[d->buckets[p] - 1], key)) p = (p + 1) & (d->capacity - 1);");
    output.append_line("    return p;");
    output.append_line("}");
    output.append_line("static void rl_dict_rebuild(rl_dict *d) {");
    output.append_line("    memset(d->buckets, 0, d->capacity * sizeof(*d->buckets));");
    output.append_line("    for (int32_t i = 0; i < d->keys->length; ++i) d->buckets[rl_dict_bucket(d, d->keys->data[i])] = (uint32_t)i + 1;");
    output.append_line("}");
    output.append_line("static void rl_dict_capacity(rl_dict *d, uint64_t entries) {");
    output.append_line("    if (entries > INT32_MAX) { fputs(\"Dict capacity exceeds INT32_MAX\\n\", stderr); exit(1); }");
    output.append_line("    uint64_t capacity = 16;");
    output.append_line("    while (capacity < entries * 2) capacity *= 2;");
    output.append_line("    if (capacity <= d->capacity) return;");
    output.append_line("    if (capacity > SIZE_MAX / sizeof(*d->buckets)) { fputs(\"Dict capacity too large\\n\", stderr); exit(1); }");
    output.append_line("    d->buckets = rl_allocate((size_t)capacity * sizeof(*d->buckets)); d->capacity = (size_t)capacity;");
    output.append_line("    rl_dict_rebuild(d);");
    output.append_line("}");
    output.append_line("static rl_dict *rl_dict_new(int32_t capacity, int32_t key_kind, int32_t reference, int32_t string) {");
    output.append_line("    if (capacity < 0) { fputs(\"negative Dict capacity\\n\", stderr); exit(1); }");
    output.append_line("    if (key_kind == 1 && !string) { fputs(\"Dict string key kind requires String keys\\n\", stderr); exit(1); }");
    output.append_line("    rl_dict *d = rl_allocate(sizeof(*d)); d->kind = key_kind == 1 ? 1 : reference ? 2 : 0;");
    output.append_line("    d->keys = rl_vec_new(capacity); d->values = rl_vec_new(capacity); rl_dict_capacity(d, (uint64_t)capacity); return d;");
    output.append_line("}");
    output.append_line("static int64_t rl_dict_find(rl_dict *d, rl_slot key) { return (int64_t)d->buckets[rl_dict_bucket(d, key)] - 1; }");
    output.append_line("static int64_t rl_dict_entry(rl_dict *d, rl_slot key, rl_slot value) {");
    output.append_line("    int64_t index = rl_dict_find(d, key); if (index >= 0) return index;");
    output.append_line("    rl_dict_capacity(d, (uint64_t)d->keys->length + 1);");
    output.append_line("    index = d->keys->length;");
    output.append_line("    size_t bucket = rl_dict_bucket(d, key);");
    output.append_line("    rl_vec_push(d->keys, key); rl_vec_push(d->values, value); d->buckets[bucket] = (uint32_t)index + 1; return index;");
    output.append_line("}");
    output.append_line("static void rl_dict_set(rl_dict *d, rl_slot key, rl_slot value) { int64_t i = rl_dict_entry(d, key, value); d->values->data[i] = value; }");
    output.append_line("static rl_optional *rl_dict_get(rl_dict *d, rl_slot key) { int64_t i = rl_dict_find(d, key); return i < 0 ? NULL : rl_some(d->values->data[i]); }");
    output.append_line("static rl_optional *rl_dict_remove(rl_dict *d, rl_slot key) {");
    output.append_line("    int64_t i = rl_dict_find(d, key); if (i < 0) return NULL;");
    output.append_line("    rl_optional *value = rl_some(d->values->data[i]);");
    output.append_line("    size_t count = (size_t)(d->keys->length - i - 1);");
    output.append_line("    memmove(d->keys->data + i, d->keys->data + i + 1, count * sizeof(rl_slot));");
    output.append_line("    memmove(d->values->data + i, d->values->data + i + 1, count * sizeof(rl_slot));");
    output.append_line("    d->keys->data[--d->keys->length] = (rl_slot){0}; d->values->data[--d->values->length] = (rl_slot){0};");
    output.append_line("    rl_dict_rebuild(d); return value;");
    output.append_line("}");
    output.append_line("static void rl_dict_clear(rl_dict *d) {");
    output.append_line("    memset(d->keys->data, 0, (size_t)d->keys->length * sizeof(rl_slot));");
    output.append_line("    memset(d->values->data, 0, (size_t)d->values->length * sizeof(rl_slot));");
    output.append_line("    d->keys->length = d->values->length = 0; rl_dict_rebuild(d);");
    output.append_line("}");
    output.append_line("static rl_vec *rl_dict_snapshot(rl_vec *source) {");
    output.append_line("    rl_vec *result = rl_vec_new(source->length); result->length = source->length;");
    output.append_line("    if (source->length) memcpy(result->data, source->data, (size_t)source->length * sizeof(rl_slot));");
    output.append_line("    return result;");
    output.append_line("}");
    output.append_line("static rl_slot rl_dict_value_at(rl_dict *d, int64_t i) { return i < 0 || i >= d->values->length ? (rl_slot){0} : d->values->data[i]; }");
    output.append_line("static void rl_dict_set_at(rl_dict *d, int64_t i, rl_slot value) { if (i >= 0 && i < d->values->length) d->values->data[i] = value; }");
}
