import std.string_builder

pub def emit_string_runtime(output: StringBuilder) -> Void {
    output.append_line("struct rl_string { const unsigned char *data; int64_t length; };");
    output.append_line("static rl_string *rl_string_new(const unsigned char *data, int64_t length) {");
    output.append_line("    rl_string *s = rl_allocate(sizeof(*s));");
    output.append_line("    unsigned char *bytes = rl_allocate((size_t)length + 1);");
    output.append_line("    if (length) memcpy(bytes, data, (size_t)length);");
    output.append_line("    s->data = bytes; s->length = length; return s;");
    output.append_line("}");
    output.append_line("static int32_t rl_string_compare(rl_string *a, rl_string *b) {");
    output.append_line("    int64_t n = a->length < b->length ? a->length : b->length;");
    output.append_line("    int cmp = memcmp(a->data, b->data, (size_t)n);");
    output.append_line("    if (cmp) return cmp < 0 ? -1 : 1;");
    output.append_line("    return (a->length > b->length) - (a->length < b->length);");
    output.append_line("}");
    output.append_line("static rl_string *rl_string_concat(rl_string *a, rl_string *b) {");
    output.append_line("    if (b->length > INT64_MAX - a->length || (uint64_t)(a->length + b->length) >= SIZE_MAX) { fputs(\"string too large\\n\", stderr); exit(1); }");
    output.append_line("    rl_string *s = rl_allocate(sizeof(*s)); s->length = a->length + b->length;");
    output.append_line("    unsigned char *bytes = rl_allocate((size_t)s->length + 1);");
    output.append_line("    memcpy(bytes, a->data, (size_t)a->length); memcpy(bytes + a->length, b->data, (size_t)b->length);");
    output.append_line("    s->data = bytes; return s;");
    output.append_line("}");
    output.append_line("static int32_t rl_string_contains(rl_string *a, rl_string *b) {");
    output.append_line("    if (!b->length) return 1;");
    output.append_line("    for (int64_t i = 0; i <= a->length - b->length; ++i) if (!memcmp(a->data + i, b->data, (size_t)b->length)) return 1;");
    output.append_line("    return 0;");
    output.append_line("}");
    output.append_line("static int32_t rl_string_starts_with(rl_string *a, rl_string *b) { return b->length <= a->length && !memcmp(a->data, b->data, (size_t)b->length); }");
    output.append_line("static int32_t rl_string_ends_with(rl_string *a, rl_string *b) { return b->length <= a->length && !memcmp(a->data + a->length - b->length, b->data, (size_t)b->length); }");
    output.append_line("static int32_t rl_string_byte(rl_string *s, int32_t i) { return i < 0 || i >= s->length ? -1 : s->data[i]; }");
    output.append_line("static int32_t rl_string_find_char(rl_string *s, int32_t c, int32_t start) {");
    output.append_line("    for (int64_t i = start < 0 ? 0 : start; i < s->length; ++i) if (s->data[i] == c) return rl_bits((uint32_t)i);");
    output.append_line("    return -1;");
    output.append_line("}");
    output.append_line("static rl_string *rl_string_substring(rl_string *s, int32_t start, int32_t length) {");
    output.append_line("    if (start < 0) start = 0;");
    output.append_line("    if (start >= s->length || length <= 0) return rl_string_new((const unsigned char *)\"\", 0);");
    output.append_line("    int64_t n = length; if (n > s->length - start) n = s->length - start;");
    output.append_line("    return rl_string_new(s->data + start, n);");
    output.append_line("}");
    output.append_line("static rl_string *rl_integer_string(int64_t value) { char buf[32]; int n = snprintf(buf, sizeof(buf), \"%lld\", (long long)value); return rl_string_new((const unsigned char *)buf, n); }");
    output.append_line("static int64_t rl_bits64(uint64_t x) { int64_t y; memcpy(&y, &x, 8); return y; }");
    output.append_line("static int64_t rl_add64(int64_t a,int64_t b) { return rl_bits64((uint64_t)a+(uint64_t)b); }");
    output.append_line("static int64_t rl_sub64(int64_t a,int64_t b) { return rl_bits64((uint64_t)a-(uint64_t)b); }");
    output.append_line("static int64_t rl_mul64(int64_t a,int64_t b) { return rl_bits64((uint64_t)a*(uint64_t)b); }");
    output.append_line("static int64_t rl_neg64(int64_t a) { return rl_bits64(0u-(uint64_t)a); }");
    output.append_line("static int64_t rl_div64(int64_t a,int64_t b) { if(!b) rl_zero(); if(a==INT64_MIN && b==-1) return INT64_MIN; return a/b; }");
    output.append_line("static int64_t rl_rem64(int64_t a,int64_t b) { if(!b) rl_zero(); if(a==INT64_MIN && b==-1) return 0; return a%b; }");
}
